# attogram/shared-media-gallery - codeclimate.yml - v0.0.5
version: "2"
exclude_patterns:
- "vendor/"
- "config/"
- "src/Attogram/SharedMedia/Orm/Base/"
- "src/Attogram/SharedMedia/Orm/Map/"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess: # allow Object::method()
        enabled: false
      Controversial/Superglobals: # allow $_SERVER, $_GET, $_POST, ...
        enabled: false
      Design/DevelopmentCodeFragment: # allow print_r()
        enabled: false
      Design/ExitExpression: # allow exit
        enabled: false
  phan:
    enabled: true
    checks:
      PhanTypeMismatchArgument:
        enabled: false
      PhanTypeMismatchForeach:
        enabled: false
      PhanTypeMismatchProperty:
        enabled: false
      PhanNonClassMethodCall:
        enabled: false
      PhanUndeclaredClass:
        enabled: false
      PhanUndeclaredClassCatch:
        enabled: false
      PhanUndeclaredClassConstant:
        enabled: false
      PhanUndeclaredClassInstanceof:
        enabled: false
      PhanUndeclaredClassMethod:
        enabled: false
      PhanUndeclaredExtendedClass:
        enabled: false
      PhanUndeclaredInterface:
        enabled: false
      PhanUndeclaredMethod:
        enabled: false
      PhanUndeclaredProperty:
        enabled: false
      PhanUndeclaredStaticMethod:
        enabled: false
      PhanUndeclaredTypeParameter:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 63
  csslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
